import React from 'react';
import {View, Text, StyleSheet, Linking} from 'react-native';
import MainScreen from '../../components/containers/MainScreen';
import MainFrame from '../../components/containers/MainFrame';
import Header from '../../components/headers/Header';
import {ScrollView} from 'react-native-gesture-handler';
import {COLORS, FONTS, SIZES, SPACING} from '../../styles/theme';
import {windowHeight, windowWidth} from '../../utils/Dimensions';
import ListTermsAndConditions from '../../components/listItem/ListTermsAndConditions';

const TermsAndConditions = () => {
  return (
    <MainScreen>
      <Header title="Terms and Conditions" />
      <MainFrame fullscreen>
        <ScrollView showsVerticalScrollIndicator={false}>
          <View style={styles.container}>
            <Text style={styles.title}>Terms and Conditions</Text>
            <Text style={styles.sectionTitle}>1. General Terms</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="1.1."
                body="By accessing and placing an order with Retriever, you confirm that you are in agreement with and bound by the terms of service contained in the Terms & Conditions outlined below. These terms apply to the entire application, website, and any email or other type of communication between you and Retriever."
              />
              <ListTermsAndConditions
                sectionNumber="1.2."
                body="Under no circumstances shall the team be liable for any direct, indirect, special, or consequential damages, including but not limited to, loss of data or profits, arising out of use, or inability to use, the materials on this site even if the team or authorized representatives has been advised of the possibility of equipment or data, you assume any costs thereof."
              />
              <ListTermsAndConditions
                sectionNumber="1.3."
                body="Retriever will not be responsible for any outcome that may occur during the usage of our resources. We reserve the right to change prices and revise the resources usage policy at any moment."
              />
            </View>
            <Text style={styles.sectionTitle}>2. License</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="2.1."
                body="Retriever grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use our service strictly in accordance with the terms of this Agreement."
              />
              <ListTermsAndConditions
                sectionNumber="2.2."
                body="These Terms & Conditions are a contract between you and Retriever (referred to in these Terms & Conditions as “Retriever”, “us”, “we”, or “our”), the provider of the Retriever application and website and the services accessible from the Retriever application and website (which are collectively referred to in these Terms & Conditions as the “Retriever Service”)."
              />
              <ListTermsAndConditions
                sectionNumber="2.3."
                body="You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use the Service. In these Terms & Conditions, “you” refers both to you as an individual and to the entity you represent. If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account without notice."
              />
            </View>
            <Text style={styles.sectionTitle}>
              3. Definitions and key terms
            </Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="3.1."
                body="For this Terms & Conditions:"
              />
              <ListTermsAndConditions
                sectionNumber="3.1.1"
                keyword="Application: "
                body="the mobile application, Retriever, which is used for the Service."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.2"
                keyword="Cookie: "
                body="small amount of data generated by an application or website and saved by your web browser and mobile device. It is used to identify your browser, provide analytics, and remember information about you such as your language preferences or login information."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.3"
                keyword="Company: "
                body="when this policy mentions “Company”, “we”, “us”, or “our”, it refers to Retriever Tech Corp., Block 10 Lot 14 Victoria Village, Matina Aplaya, Davao City that is responsible for your information under this Privacy Policy."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.4"
                keyword="Country: "
                body="where Retriever or the owners/founders of Retriever are based, in this case, the Philippines."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.5"
                keyword="Customer: "
                body="refers to the company, organization, or person that signs up to use the Retriever Service to manage the relationships with your consumers or service users."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.6"
                keyword="Device: "
                body="any internet-connected device such as a phone, tablet, computer, or any other device that can be used to visit Retriever and use the services."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.7"
                keyword="Delivery: refers to the transportation and/or logistics of goods be it food, beverages, groceries or other products via the use of Retriever."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.8"
                keyword="IP address: "
                body="Every device connected to the Internet is assigned a number known as an Internet protocol (IP) address. These numbers are usually assigned in geographic blocks. An IP address can often be used to identify the location from which a device is connecting to the Internet."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.9"
                keyword="Merchant Partner: refers to third party individuals or organizations partnered with Retriever who provide the relevant goods to the consumer via our Platform."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.10"
                keyword="Order: the act of using the Retriever App to buy the goods or other products from the in app store of the Merchant Partner and have it delivered to a chosen location."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.11"
                keyword="Personnel: "
                body="refers to those individuals who are employed by Retriever or are under contract to perform a service on behalf of one of the parties."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.12"
                keyword="Personal Data: "
                body="Any information that directly, indirectly, or in connection with other information - including a personal identification number - allows for the identification or identifiability of a natural person."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.13"
                keyword="Platform: refers to the Application, Software and any other platform, portal or website which Retriever owns, operates or otherwise makes available to Consumers and/or Partners for the purposes of or in connection with the Service and/or Solution."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.14"
                keyword="Service: "
                body="refers to the service provided by Retriever as described in the relative terms (if available) and on this platform."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.15"
                keyword="Retriever Wallet: refers to the in-app currency of Retriever which you can use to pay for the services in the app."
              />
              <ListTermsAndConditions
                sectionNumber="3.1.16"
                keyword="Third-party service: "
                body="refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide our content or whose products or services we think may interest you."
              />
              <View style={styles.bodyWrapper1}>
                <Text style={styles.sectionNumber}>3.1.17.</Text>
                <Text style={styles.body}>
                  <Text style={{fontStyle: 'italic'}}>Website: </Text>
                  Retriever’s site, which can be accessed via this URL:{' '}
                  <Text
                    style={{color: 'blue', textDecorationLine: 'underline'}}
                    onPress={() => Linking.openURL(`http://www.retriever.ph/`)}>
                    http://www.retriever.ph/
                  </Text>
                  .
                </Text>
              </View>
              <ListTermsAndConditions
                sectionNumber="3.1.18"
                keyword="You: "
                body="a person or entity that is registered with Retriever to use the Services."
              />
            </View>
            <Text style={styles.sectionTitle}>4. Restrictions</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="4.1."
                body="You agree not to, and you will not permit others to:"
              />
              <ListTermsAndConditions
                sectionNumber="4.1.1"
                body="License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the service or make the platform available to any third party."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="4.1.2"
                body="Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the service."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="4.1.3"
                body="Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of or its affiliates, partners, suppliers, or the licensors of the service."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>5. Orders</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="5.1."
                body="Retriever is an Application that allows you to place orders for food and beverages from food and beverages providers (“Merchant Partners”), such orders are to be delivered to you by independent third-party delivery service providers (“Riders”). We do not own, sell or resell any food or beverages items and do not control the Merchant Partners, the Riders, or any service provided by them. You understand that any order that you place shall be subject to product availability and delivery location serviceability of the Merchant Partners and/or Riders."
              />
              <ListTermsAndConditions
                sectionNumber="5.2."
                body="When you place an Order with Retriever, we will confirm your order by sending you a confirmation email containing the Order receipt. Where applicable, Orders will include delivery fees and any applicable tax (e.g. good and service tax, value-added tax, etc.)"
              />
              <ListTermsAndConditions
                sectionNumber="5.3."
                body="Special Instructions - Retriever and the Merchant Partner (as the case may be) reasonably endeavor to comply with your special instructions for an Order. However in some cases where this is not feasible, possible, or commercially reasonable, Retriever and/or the Merchant Partner reserve the right to proceed to prepare the Order in accordance with standard operating procedures. Neither Retriever nor the Merchant Partner shall be responsible to replace or refund an Order which does not conform to special instructions provided by you."
              />
              <ListTermsAndConditions
                sectionNumber="5.4."
                body="Allergens - Retriever is not obliged to provide ingredient information or allergen information on the Platforms. Further, Retriever does not guarantee that the Goods sold by the Merchant Partner are free of allergens. If you have allergies, allergic reactions, or dietary restrictions and requirements, please contact the Merchant Partner before placing an Order on our Platform."
              />
              <ListTermsAndConditions
                sectionNumber="5.5."
                body="Please note that your order may be subject to additional terms and conditions provided by the Merchant Partner."
              />
              <ListTermsAndConditions
                sectionNumber="5.6."
                body="Prior to placing the order"
              />
              <ListTermsAndConditions
                sectionNumber="5.6.1"
                body="You are required to provide the delivery address in order for the Platform to display the Merchant Partner available in your delivery area."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.6.2"
                body="Once you select a Merchant Partner, you will be taken to that Merchant Partner’s menu page for you to select and add your Goods to the cart."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.7."
                body="Placing the Order"
              />
              <ListTermsAndConditions
                sectionNumber="5.7.1"
                body="To complete an order, please follow the onscreen instructions after clicking “Cart”. You may be required to provide additional details for us to complete your order. You are required to review and confirm that all the information and promo codes (if applicable) are true, accurate, and complete before you click “PLACE ORDER”. An Order is successfully placed when you received confirmation from the Merchant Partner and an email confirmation containing your Order receipt from us."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.8."
                body="All Orders and delivery bookings placed on the application are treated as confirmed. You shall not be entitled to cancel your Order once you have received a confirmation."
              />
              <ListTermsAndConditions
                sectionNumber="5.9."
                body="You remain liable to pay the order value in full where:"
              />
              <ListTermsAndConditions
                sectionNumber="5.9.1."
                body="You are not present or do not show up at the designated delivery location after ten (10) minutes from the time that the Rider arrives at the designated delivery location or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.9.2."
                body="You are unreachable physically or uncountable after ten (10) minutes from the time that the Rider arrives at the designated location"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.10."
                body="Retriever, the Merchant Partner and/or Rider may not process your booking for Order in the event of any of the following:"
              />
              <ListTermsAndConditions
                sectionNumber="5.10.1."
                body="You are unavailable on the mobile device at the time of the call for confirming the order or otherwise uncontactable,"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.10.2."
                body="If the requested delivery location falls outside the delivery zone offered in the Application,"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.10.3."
                body="There is a lack of information, direction, or authorization from you at the time of the delivery,"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.10.4"
                body="You are not present or do not show up at the designated delivery location to collect your Order, or you are unreachable physically or uncontactable after ten (10) minutes from the time that the Rider arrives at the designated delivery location or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.10.5."
                body="unavailability of items ordered."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.11."
                body="You are responsible for ensuring that the delivery details entered by you in respect of the Order on the Application are accurate and complete. Retriever shall not be liable in the event of late delivery or non-delivery of food and beverage items that you order by reason of erroneous delivery details entered by you on the Application."
              />
              <ListTermsAndConditions
                sectionNumber="5.12."
                body="After the delivery of the Order items you ordered, you shall solely be liable for demurrage or loss, damage, contamination, soiling, or detention of the Order items (including but not limited to containers) whether caused directly or indirectly by you or any person acting on your behalf."
              />
              <ListTermsAndConditions
                sectionNumber="5.13."
                body="Persons placing an order for alcohol from any of the Merchant Partners must be at least eighteen (18) years old. Alcoholic beverages can only be sold and delivered to persons who are at least eighteen (18)  years of age. By placing an order that includes alcohol, you confirm that you are at least eighteen (18) years old. The Rider or Merchant Partner will have the right to refuse to deliver or provide any alcoholic products to any person who at the time of the delivery"
              />
              <ListTermsAndConditions
                sectionNumber="5.13.1."
                body="Does not appear to be at least eighteen (18) years old or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.13.2."
                body="Cannot prove that he/she is at least eighteen (18) years old or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.13.3."
                body="Is, or appears to be, under the influence of either alcohol or drugs at the time of the delivery, and in such an event you agree that Retriever, the Rider, and or the Merchant Partner shall not be liable to make any refund to you for payment already made by you."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="5.14."
                body="Retriever has sole discretion in adopting any User Charge policy for Retriever Service and may include, Platform Fees, Delivery Fees, and Small Order Fees."
              />
              <ListTermsAndConditions
                sectionNumber="5.15."
                body="Retriever reserves the right to cancel and/or suspend, deactivate or terminate your Retriever account in its sole discretion if it reasonably believes or detects fraudulent activity or behavior associated with your Retriever account and/or with your Order."
              />
              <ListTermsAndConditions
                sectionNumber="5.16."
                body="In the event where the physical store is closed while the Store in-app is available and you have placed an order, we will cancel your order. Any amount used in payment for the order will be refunded to you via the Retriever Wallet."
              />
            </View>
            <Text style={styles.sectionTitle}>6. Prices</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="6.1."
                body="Prices quoted on the Platform for food and beverages items are determined solely by the Merchant Partner and are listed for informational purposes only."
              />
              <ListTermsAndConditions
                sectionNumber="6.2."
                body="The way we display the prices of our Goods may vary depending on the Merchant Partner, and the prices reflected on our Platforms may:"
              />
              <ListTermsAndConditions
                sectionNumber="6.2.1."
                body="Include GST, VAT, or such other equivalent tax; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="6.2.2."
                body="Exclude GST, VAT, or such other equivalent tax."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="6.3."
                body="A breakdown of the prices and additional charges is displayed before checkout. When you place an order, you agree to all amounts, additional charges, and the final “Total” amount which is displayed to you."
              />
              <ListTermsAndConditions
                sectionNumber="6.4."
                body="Delivery fees are chargeable on every Order unless:"
              />
              <ListTermsAndConditions
                sectionNumber="6.4.1."
                body="You have a valid promotional or discount code and apply it at Checkout; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="6.4.2."
                body="Unless stated otherwise/"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="6.5."
                body="Prices indicated on the Platforms are at the time of each Order and may be subject to change."
              />
            </View>
            <Text style={styles.sectionTitle}>7. Payment Method</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions body="By using the Retriever mobile application supplied to you by the Company’s affiliated company/ies (the “Application”), and downloading, installing, or using any associated software supplied by the Company (“the Software”) which overall purpose is to enable persons seeking to establish an account with the Company and use the Retriever Wallet (the “Retriever Wallet” and generally, the “Service”), you hereby expressly acknowledge and agree to be bound by these Terms of Use, and any future amendments and additions to these Terms of Use as published from time to time at https://www.retriever.ph or through the Application, and your continued use of the Service after any such changes, whether or not reviewed by you, shall constitute your consent and acceptance of the revised Terms of Use. Notwithstanding the foregoing, the Company will provide ten (10) business days’ notice of any changes, which the Company in its reasonable discretion deem material, to these Terms of Use following which your continued use of the Service will be deemed to confirm your acceptance of such changes." />
              <ListTermsAndConditions
                sectionNumber="7.1."
                body="Type of payments that can be made with the Retriever Wallet:"
              />
              <ListTermsAndConditions
                sectionNumber="7.1.1."
                body="Prices indicated on the Platforms are at the time of each Order and may be subject to change."
                keyword
              />
              <View style={styles.subBodyContainer}>
                <ListTermsAndConditions
                  sectionNumber="7.1.1.1."
                  body="The Retriever wallet may be used only for the sale and purchase of goods and services from all transportation providers, Merchant Partners in the Application, PROVIDED HOWEVER that no payments in violation of the provisions of these Terms & Conditions, including the Acceptable Use Policy (below) shall be permitted."
                  keyword
                />
              </View>
              <ListTermsAndConditions
                sectionNumber="7.1.2."
                body="User Transaction Statement:"
                keyword
              />
              <View style={styles.subBodyContainer}>
                <ListTermsAndConditions
                  sectionNumber="7.1.2.1."
                  body="A full statement of the User's transactions may be downloaded upon a request from Retriever Tech Corp. via the support page."
                  keyword
                />
              </View>
              <ListTermsAndConditions
                sectionNumber="7.1.3."
                body="Fraudulent activity or stolen e-money:"
                keyword
              />
              <View style={styles.subBodyContainer}>
                <ListTermsAndConditions
                  sectionNumber="7.1.3.1."
                  body="You agree to immediately notify the Company by sending an email to support@retriever.ph of any fraudulent activity or theft of funds in the Retriever Wallet of which you become aware."
                  keyword
                />
              </View>
              <ListTermsAndConditions
                sectionNumber="7.1.4."
                body="The Company has the right to suspend, or later reverse, the processing of any transaction where it reasonably believes that the transaction may be fraudulent, illegal, or involves any criminal activity or where the Company reasonably believes you to be in breach of the Terms & Conditions."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.1.5."
                body="The Company reserves the right to suspend the use of your account entirely, disable the cashless feature in the Retriever Wallet or block any financial instruments e.g credit or debit card where it reasonably believes that the account activity may be fraudulent, illegal, or involves any criminal activity or where the Company reasonably believes you to be in breach of the Terms & Conditions."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.1.6."
                body="Unless the context dictates otherwise, references in these Terms & Conditions to the Retriever Wallet shall include all such stored value facility e-wallets issued to Users by the Company to include the Restricted Retriever Wallet, the Standard Retriever Consumer Wallet, the Retriever Rider Wallet, and the Retriever Merchant Wallet."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.2."
                body="Funding Methods for use of the Service"
                fontStyle={{...FONTS.italic}}
              />
              <ListTermsAndConditions
                sectionNumber="7.2.1."
                body="You can choose to pay for an Order by funding your Retriever Wallet using any of the different payment methods offered on the Platforms including:"
                keyword
              />
              <View style={styles.subBodyContainer}>
                <ListTermsAndConditions
                  sectionNumber="7.2.1.1."
                  body="Our payment partners: Dragonpay via Online Bank Transfer, Credit Card, Debit Card, GCash, Paymaya;"
                  keyword
                />
                <ListTermsAndConditions
                  sectionNumber="7.2.1.2."
                  body="Such other payment methods we offer from time to time."
                  keyword
                />
              </View>
              <ListTermsAndConditions
                sectionNumber="7.2.2."
                body="In the case of debit or credit cards as Funding Sources, you agree that we may issue a reasonable authorization hold, which is not an actual charge against your card, in order to verify your payment method via your card. The hold may appear in your statement as “pending”. The authorization hold is issued as a preventive measure against any unauthorized or fraudulent usage of your card."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.2.3."
                body="Your Retriever Wallet will hold Philippines Peso currency only."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.2.4."
                body="When you make a payment, you are liable to the Company for the full amount of the payment sent to you plus any fees if the payment is later invalidated for any reason including but not limited to claims, chargebacks, or if there is a reversal of the payment."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.2.5."
                body="You shall be responsible to resolve any dispute with your debit or credit card company on your own."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.3."
                body="You can choose to pay for an Order using Cash-on-Delivery if funding your Retriever Wallet is not available to you."
              />
              <ListTermsAndConditions
                sectionNumber="7.4."
                body="Retriever reserve the right to offer additional payment methods and/or remove existing payment methods at any time at its sole discretion. If you choose to pay using online payment options, the payment shall be processed by our third-party payment service provider(s). With your consent, your credit card/payment information will be stored with our third-party payment service provider(s) for future orders. Retriever does not store your credit card or payment information."
              />
              <ListTermsAndConditions
                sectionNumber="7.5."
                body="You must ensure that you have sufficient funds on your credit card and debit card to fulfill the funding of your Retriever Wallet. Insofar as required, Retriever takes responsibility for payments made on our Platforms including refunds, chargebacks, cancellations, and dispute resolution, provided if reasonable and justifiable and in accordance with these Terms."
              />
              <ListTermsAndConditions sectionNumber="7.6." body="Charging" />
              <ListTermsAndConditions
                sectionNumber="7.6.1."
                body="You will only be charged the Order’s Total amount once the Rider has delivered the Order to your designated delivery location."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="7.6.2."
                body="Your payment is in process and locked in once the Merchant Partner has confirmed your Order and the Rider has accepted the delivery."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>8. Delivery</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="8.1."
                body="Delivery Areas"
              />
              <ListTermsAndConditions
                sectionNumber="8.1.1."
                body="You understand that our Merchant Partners offer their Goods in specific delivery areas and our Merchant Partners vary from delivery area to delivery area. By entering your address on the Platform, you will see the Merchant Platform that we make available to you at the time. Delivery areas may expand, shrink or change depending on weather conditions and situations of force majeure."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.2."
                body="Delivery Time"
              />
              <ListTermsAndConditions
                sectionNumber="8.2.1."
                body="Retriever shall deliver your Order to the delivery address provided by you. You may choose for your Order to be delivered “Deliver Now” or scheduled for a specific time. An estimated delivery time shall vary depending on factors that are not controlled by us (e.g. order quantity, distance, time of day (peak periods), weather conditions, traffic conditions, etc.). You can view the remaining delivery time of an Order when you click “Cart” on the Platforms. You acknowledge that the delivery time we provide is only an estimate and Orders may arrive earlier or later. To ensure that you do not miss a delivery of an Order, you should ensure that either you or someone is at the delivery location to receive the Order once an Order is placed. If your Order contains Alcohol or Tobacco (if applicable) and you or the recipient is or appears to be below the legal age, or fails to provide a valid proof of ID, Retriever reserves the right not to deliver your order to you."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.3."
                body="In cases where we attempt to deliver an Order but we are unable to do so due to the reasons caused by you, including but not limited to:"
              />
              <ListTermsAndConditions
                sectionNumber="8.3.1."
                body="No one was present or available to receive the Order; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.3.2."
                body="The customer was uncontactable despite attempts to reach the customer via the phone number provided; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.3.3."
                body="Lack of appropriate or sufficient access to deliver the Order successfully;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.3.4."
                body="lack of a suitable or secure location to leave the Order; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.3.5."
                body="In the case of Restricted Goods, the customer did not meet the statutory age requirements or delivery did not deem it safe or appropriate for the customer to receive the Restricted Goods."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.4."
                body="No-show Cancellations"
              />
              <ListTermsAndConditions
                sectionNumber="8.4.1."
                body="If you remain uncontactable or fail to receive the Order within ten (10) minutes from the time the order arrives at your delivery address, Retriever reserves the right to cancel the order without refund or remedy to you."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.5."
                body="Wrong Order, Missing Items, Defective Goods"
              />
              <ListTermsAndConditions
                sectionNumber="8.5.1."
                body="Upon receipt of your order, if you discover that there are issues with your Order (e.g. wrong order, defective order, or missing items) please contact customer support via support channels (support@retriever.ph or @retrieverph) immediately. In some cases, Retriever may request photographic proof and/or additional information to properly investigate the issue with your Order. If we determine that the Order and/or Goods you received are not of satisfactory condition or quality, we will compensate you for your Order or parts of your Order."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="8.5.2."
                body="The Merchant Partner shall be solely responsible for any warranty in relation to, and quality of, the food and beverage products sold to you unless it is proven that the Order was delivered in an adulterated state caused by the negligence and willful acts of the Rider."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>9. Return and Refund Policy</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="9.1."
                body="You have the right to refund or exchange an Order only if:"
              />
              <ListTermsAndConditions
                sectionNumber="9.1.1."
                body="The Merchant Partner has made an error in your Order;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="9.1.2."
                body="The Rider has made an error in your Order;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="9.1.3."
                body="The Application experiences bugs and/or other errors that have caused your order to be unclaimable."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="9.2."
                body="Only if the above conditions have been met will we give a refund"
              />
              <ListTermsAndConditions
                sectionNumber="9.2.1."
                body="The refund will be in the form of credits to your Retriever Wallet."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="9.2.2."
                body="The refund will only include the Order amount and not the delivery fee."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="9.3."
                body="There is no refund policy for Retriever Wallet."
              />
              <ListTermsAndConditions
                sectionNumber="9.3.1."
                body="Once you Cash into Retriever Wallet, you agree to the Terms of Use stipulating that there is a no refund policy."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>10. Promotions</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="10.1."
                body="If you wish to use or apply any promotion codes or discounts, you must enter the available promotion codes or discounts upon checkout of the Cart."
              />
              <ListTermsAndConditions
                sectionNumber="10.2."
                body="We may, from time to time, include contests, promotions, sweepstakes, or other activities (“Promotions”) that require you to submit material or information concerning yourself."
              />
              <ListTermsAndConditions
                sectionNumber="10.3."
                body="Please note that all Promotions may be governed by separate rules that may contain certain eligibility requirements, such as restrictions as to age and geographical location. All promotion codes and discounts are subject to their specific terms and conditions, and are mutually exclusive, and cannot be combined with other promotions unless otherwise stated."
              />
              <ListTermsAndConditions
                sectionNumber="10.4."
                body="You are responsible to read all Promotions rules to determine whether or not you are eligible to participate."
              />
              <ListTermsAndConditions
                sectionNumber="10.5."
                body="If you enter any Promotion, you agree to abide by and comply with all Promotions Rules."
              />
              <ListTermsAndConditions
                sectionNumber="10.6."
                body="Additional terms and conditions may apply to purchases of goods or services on or through the Services, which terms and conditions are made a part of this Agreement by reference."
              />
              <ListTermsAndConditions
                sectionNumber="10.7."
                body="The price payable for the discounted food or beverage item may be rounded and will be set out on the checkout page for your Order. You agree that we are not obliged to accept late submission of promotion codes and discounts after the checkout process has been completed."
              />
              <ListTermsAndConditions
                sectionNumber="10.8."
                body="We will not be liable for any losses, damages, costs, and expenses suffered or incurred as a result of the theft or illegal or fraudulent usage of any promo codes and discounts. We may take any action against you if you have been found to be using any promotion codes and discounts illegally or fraudulently, including without limitation, suspending or terminating your user account."
              />
            </View>
            <Text style={styles.sectionTitle}>11. Your Suggestions</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="11.1."
                body="Any feedback, comments, ideas, improvements, or suggestions (collectively, “Suggestions”) provided by you to us concerning the service shall remain the sole and exclusive property of us."
              />
              <ListTermsAndConditions
                sectionNumber="11.2."
                body="We shall be free to use, copy, modify, publish, or redistribute the Suggestion for any purpose and in any way without any credit or any compensation to you."
              />
            </View>
            <Text style={styles.sectionTitle}>12. Your Consent</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="12.1."
                body="We’ve updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our platform and how it’s being used."
              />
              <ListTermsAndConditions
                sectionNumber="12.2."
                body="By using our service, registering an account, or making a purchase, you hereby consent to our Terms & Conditions."
              />
            </View>
            <Text style={styles.sectionTitle}>13. Links to Other Websites</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="13.1."
                body="Our service may contain links to other websites that are not operated by Us. If You click on a third-party link, You will be directed to that third party’s site."
              />
              <ListTermsAndConditions
                sectionNumber="13.2."
                body="We strongly advise You to review the Terms & Conditions of every site You visit."
              />
              <ListTermsAndConditions
                sectionNumber="13.3."
                body="We have no control over and assume no responsibility for the content, Terms & Conditions, or practices of any third-party sites or services."
              />
            </View>
            <Text style={styles.sectionTitle}>14. Cookies</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="14.1."
                body="We use “Cookies” to identify the areas of our website that you have visited."
              />
              <ListTermsAndConditions
                sectionNumber="14.2."
                body="A cookie is a small piece of data stored on your computer or mobile device by your web browser. We use cookies to enhance the performance and functionality of our service but are non-essential to their use. However, without these cookies, certain functionality like videos may become unavailable or you would be required to enter your login details every time you visit our platform as we would not be able to remember that you had logged in previously."
              />
              <ListTermsAndConditions
                sectionNumber="14.3."
                body="Most web browsers can be set to disable the use of Cookies. However, if you disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally Identifiable Information in Cookies."
              />
            </View>
            <Text style={styles.sectionTitle}>
              15. Changes To Our Terms & Conditions
            </Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="15.1."
                body="You acknowledge and agree that we may stop (permanently or temporarily) providing the Service (or any features within the Services) to you or users generally at our sole discretion, without prior notice to you."
              />
              <ListTermsAndConditions
                sectionNumber="15.2."
                body="You may stop using the Service at any time. You do not need to specifically inform us when you stop using the Service."
              />
              <ListTermsAndConditions
                sectionNumber="15.3."
                body="You acknowledge and agree that if we disable access to your account, you may be prevented from accessing the Service, your account details, or any files or other materials which are contained in your account."
              />
              <ListTermsAndConditions
                sectionNumber="15.4."
                body="If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions modifications date below."
              />
            </View>
            <Text style={styles.sectionTitle}>
              16. Modifications to Our Service
            </Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="16.1."
                body="We reserve the right to modify, suspend or discontinue, temporarily or permanently, the service of any service to which it connects, with or without notice and without liability to you."
              />
            </View>
            <Text style={styles.sectionTitle}>17. Updates to Our Service</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="17.1."
                body="We may from time to time provide enhancements or improvements to the features/functionality of the service, which may include patches, bug fixes, updates, upgrades, and other modifications (“Updates”)."
              />
              <ListTermsAndConditions
                sectionNumber="17.2."
                body="Updates may modify or delete certain features and/or functionalities of the service."
              />
              <ListTermsAndConditions
                sectionNumber="17.3."
                body="You agree that we have no obligation to:"
              />
              <ListTermsAndConditions
                sectionNumber="17.3.1."
                body="Provide any Updates, or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="17.3.2."
                body="Continue to provide or enable any particular features and/or functionalities of the service to you."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="17.4."
                body="You further agree that all Updates will be:"
              />
              <ListTermsAndConditions
                sectionNumber="17.4.1."
                body="Deemed to constitute an integral part of the service,"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="17.4.2."
                body="Subject to the terms and conditions of this Agreement."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>18. Third-Party Service</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="18.1."
                body="We may display, include or make available third-party content (including data, information, applications, and other products services) or provide links to third-party websites or services (“Third-Party Services”)."
              />
              <ListTermsAndConditions
                sectionNumber="18.2."
                body="You acknowledge and agree that we shall not be responsible for any Third-Party Services, including their accuracy, completeness, timeliness, validity, copyright compliances, legality, decency, quality, or any other aspect thereof. We do not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party Services."
              />
              <ListTermsAndConditions
                sectionNumber="18.3."
                body="Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at your own risk and subject to such third parties terms and conditions."
              />
            </View>
            <Text style={styles.sectionTitle}>19. Term and Termination</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="19.1."
                body="This Agreement shall remain in effect until terminated by you or us."
              />
              <ListTermsAndConditions
                sectionNumber="19.2."
                body="We may, in sole discretion, at any time and for any or no reason, suspend or terminate this Agreement with or without prior notice."
              />
              <ListTermsAndConditions
                sectionNumber="19.3."
                body="This Agreement will terminate immediately, without prior notice from us, in the event that you fail to comply with any provision of this Agreement."
              />
              <ListTermsAndConditions
                sectionNumber="19.4."
                body="You may also terminate this Agreement by deleting the service and all copies thereof from your mobile device."
              />
              <ListTermsAndConditions
                sectionNumber="19.5."
                body="Upon termination of this Agreement, you shall cease all use of the service and delete all copies of the service from your mobile device."
              />
              <ListTermsAndConditions
                sectionNumber="19.6."
                body="Termination of this Agreement will not limit any of your rights or remedies at law or in equity in case of breach by you (during the term of this Agreement) of any of your obligations under the present Agreement."
              />
              <ListTermsAndConditions
                sectionNumber="19.7."
                body="If you are a copyright owner or such owner’s agent and believe any material from us constitutes an infringement of your copyright, please contact us setting forth the following information:"
              />
              <ListTermsAndConditions
                sectionNumber="19.7.1."
                body="A physical or electronic signature of the copyright owner or a person authorized to act on his behalf;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="19.7.2."
                body="Identification of the material that is claimed to be infringing;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="19.7.3."
                body="Your contact information, including your address, telephone number, and email address;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="19.7.4."
                body="A statement by you that you have a good faith belief that use of the material is not authorized by the copyright owners; and"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="19.7.5."
                body="The statement that the information in the notification is accurate, and under penalty of perjury you are authorized to act on behalf of the owner."
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>20. Indemnification</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="20.1."
                body="You agree to indemnify and hold us and our parents, subsidiaries, affiliates, officers, employees, agents, partners, and licensors (if any) harmless from any claim or demand, including reasonable attorneys’ fees, due to or arising out of your:"
              />
              <ListTermsAndConditions
                sectionNumber="20.1.1."
                body="Use of the service;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="20.1.2."
                body="Violation of this Agreement or any law or regulation; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="20.1.3."
                body="Violation of any righty of a third party"
                keyword
              />
            </View>
            <Text style={styles.sectionTitle}>21. No Warranties</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="21.1."
                body="The service is provided to you “AS IS” and “AS AVAILABLE” and with all faults and defects without warranty of any kind."
              />
              <ListTermsAndConditions
                sectionNumber="21.2."
                body="To the maximum extent permitted under applicable law, we, on our own behalf and on the behalf of our affiliates and our respective licensors and service providers, expressly disclaims all warranties, whether merchantability, fitness for a particular purpose, title and non-infringement, and warranties that may arise out of course of dealing, course of performance, usage or trade practice."
              />
              <ListTermsAndConditions
                sectionNumber="21.3."
                body="Without limitation to the foregoing, we provide no warranty or undertaking and make no representation of any kind that the service will meet your requirements, achieve any intended results, meet any performance or reliability standards or be error-free if any errors or defects can or will be corrected."
              />
              <ListTermsAndConditions
                sectionNumber="21.4."
                body="Without limiting the foregoing, neither we nor any provider makes any representation or warranty of any kind, express or implied:"
              />
              <ListTermsAndConditions
                sectionNumber="21.4.1."
                body="Violation of any righty of a third party"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="21.4.2."
                body="That the service will be uninterrupted or error-free;"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="21.4.3."
                body="As to the accuracy, reliability, or currency of any information or content provided through the service; or"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="21.4.4."
                body="That the service, its servers, the content, or e-mails sent from or on behalf of us are free of viruses, scripts, trojan horses, worms, malware, timebombs, or other harmful components."
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="21.5."
                body="Some jurisdictions do not allow the exclusion or limitation on implied warranties of the limitations on the applicable statutory rights of a consumer, so some or all of the above exclusions and limitations may not apply to you."
              />
            </View>
            <Text style={styles.sectionTitle}>22. Limitation of Liability</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="22.1."
                body="Notwithstanding any damages that you might incur, the entire liability of us any of our suppliers under any provision of this Agreement and your exclusive remedy for all of the foregoing shall be limited to the amount paid by you for the service."
              />
              <ListTermsAndConditions
                sectionNumber="22.2."
                body="To the maximum extent permitted by applicable law, in no event shall we or our suppliers be liable for any special, incidental, indirect, or consequential damages whatsoever (including, but not limited to, damages for loss of profits, for loss of data, or other information, for business interruption, for personal injury, for loss of privacy arising out of or in any way related to the use of our inability to use the service, the third-party software and/or third-party hardware used with the service, or otherwise in connection with any provision of this Agreement), even if we or any supplier has been advised of the possibility of such damages and even if the remedy fails of its essential purpose."
              />
              <ListTermsAndConditions
                sectionNumber="22.3."
                body="Some states/jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitations or exclusions may not apply to you."
              />
            </View>
            <Text style={styles.sectionTitle}>23. Severability</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="23.1."
                body="If any provision of this Agreement is held to be unenforceable or invalid, such provision will be changed and interpreted to accomplish the objectives of such provision to the greatest extent possible under applicable law and the remaining provisions will continue in full force and effect."
              />
              <ListTermsAndConditions
                sectionNumber="23.2."
                body="This Agreement, together with Privacy Policy and any other legal notices published by us on the Services, shall constitute the entire agreement between you and us concerning the Services."
              />
              <ListTermsAndConditions
                sectionNumber="23.3."
                body="If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect."
              />
              <ListTermsAndConditions
                sectionNumber="23.4."
                body="No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and our failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision."
              />
              <ListTermsAndConditions
                sectionNumber="23.5."
                body="YOU AND US AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THE SERVICES MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED."
              />
            </View>
            <Text style={styles.sectionTitle}>24. Waiver</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="24.1."
                body="Except as provided herein, the failure to exercise any right or to require performance of an obligation under this Agreement shall not affect a party’s ability to exercise such right or require such performance at any time thereafter nor shall be the waiver of a breach constitute waiver of any subsequent breach."
              />
              <ListTermsAndConditions
                sectionNumber="24.2."
                body="No failure to exercise and no delay in exercising, on the part of either party, any right or any power under this Agreement shall operate as a waiver of that right or power. Nor shall any single or partial exercise of any right or power under this Agreement preclude further exercise of that or any other right granted herein."
              />
              <ListTermsAndConditions
                sectionNumber="24.3."
                body="In the event of a conflict between this Agreement and any applicable purchase or other terms, the terms of this Agreement shall govern."
              />
            </View>
            <Text style={styles.sectionTitle}>
              25. Amendments to this Agreement
            </Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="25.1."
                body="We reserve the right, at its sole discretion, to modify or replace this Agreement at any time."
              />
              <ListTermsAndConditions
                sectionNumber="25.2."
                body="If a revision is material we will provide at least a 30 days notice prior to any new terms taking effect."
              />
              <ListTermsAndConditions
                sectionNumber="25.3."
                body="What constitutes a material change will be determined at our sole discretion."
              />
              <ListTermsAndConditions
                sectionNumber="25.4."
                body="By continuing to access or use our services after any revisions become effective you agree to be bound by the revised terms."
              />
              <ListTermsAndConditions
                sectionNumber="25.5."
                body="If you do not agree to the new terms, you are no longer authorized to use our service."
              />
            </View>
            <Text style={styles.sectionTitle}>26. Entire Agreement</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="26.1."
                body="The Agreement constitutes the entire agreement between you and us regarding your use of the service and supersedes any prior and contemporaneous written or oral agreements between you and us."
              />
              <ListTermsAndConditions
                sectionNumber="26.2."
                body="You may be subject to additional terms and conditions that apply when you use or purchase other services from us, which we will provide to you at the time of such use or purchase."
              />
            </View>
            <Text style={styles.sectionTitle}>27. Updates to Our Terms</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="27.1."
                body="We may change our Services and policies, and we may need to make changes to these Terms so that they accurately reflect our Services and policies."
              />
              <ListTermsAndConditions
                sectionNumber="27.2."
                body="Unless otherwise required by law, we will notify you (for example, through our Service) before we make changes to these Terms and allow you to review them before they go into effect."
              />
              <ListTermsAndConditions
                sectionNumber="27.3."
                body="Then, if you continue to use the Service, you will be bound by the updated Terms."
              />
              <ListTermsAndConditions
                sectionNumber="27.4."
                body="If you do not want to agree to these or any updated Terms, you can delete your account."
              />
            </View>
            <Text style={styles.sectionTitle}>28. Intellectual Property</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="28.1."
                body="Our platform and its entire contents, features, and functionality (including but not limited to all information, software, text, displays, images, video and audio, and the design, selection, and arrangement thereof), are owned by us, its licensors, or other providers of such material and are protected by and international copyright, trademark, patent, trade secret, and other intellectual property or proprietary rights laws."
              />
              <ListTermsAndConditions
                sectionNumber="28.2."
                body="The material may not be copied, modified, reproduced, downloaded, or distributed in any way, in whole or in part without the express prior written permission of us, unless and except as is expressly provided in these Terms & Conditions."
              />
              <ListTermsAndConditions
                sectionNumber="28.3."
                body="Any unauthorized use of the material is prohibited."
              />
            </View>
            <Text style={styles.sectionTitle}>29. Agreement to Arbitrate</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="29.1."
                body="This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR RETRIEVER’S INTELLECTUAL PROPERTY RIGHTS."
              />
              <ListTermsAndConditions
                sectionNumber="29.2."
                body="The term “dispute” means any dispute, action, or other controversies between you and us concerning the Services or this agreement, whether in contract, warranty tort, statute, regulation, ordinance, or any legal equitable basis. “Dispute” will be given the broadest possible meaning allowable under law."
              />
            </View>
            <Text style={styles.sectionTitle}>30. Notice of Dispute</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="30.1."
                body="In the event of a dispute, you or us must give the other a Notice of Dispute, which is a written statement that sets forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief requested."
              />
              <View style={[styles.bodyWrapper1, {marginLeft: 0}]}>
                <Text style={styles.sectionNumber}>30.2</Text>
                <Text style={[styles.body, {marginLeft: SPACING.x_small}]}>
                  You must send any Notice of Dispute via email to:{' '}
                  <Text
                    style={{color: 'blue', textDecorationLine: 'underline'}}>
                    support@retriever.ph
                  </Text>
                  .
                </Text>
              </View>
              <ListTermsAndConditions
                sectionNumber="30.3."
                body="We will send any Notice of Dispute to you by mail to your address if we have it, or otherwise to your email address."
              />
              <ListTermsAndConditions
                sectionNumber="30.4."
                body="You and us will attempt to resolve any dispute through informal negotiation within sixty (60) days, you or us may commence arbitration."
              />
            </View>
            <Text style={styles.sectionTitle}>31. Binding Arbitration</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="31.1."
                body="If you and us don’t resolve the dispute by informal negotiation, any other effort to resolve the dispute will be conducted exclusively by binding arbitration as described in this section."
              />
              <ListTermsAndConditions
                sectionNumber="31.2."
                body="You are giving up the right to litigate (or participate in as a party or class member) all disputes in court before judge or jury."
              />
              <ListTermsAndConditions
                sectionNumber="31.3."
                body="The dispute shall be settled by binding arbitration in accordance with the commercial arbitration rules of the Philippine Institute of Arbitrators."
              />
              <ListTermsAndConditions
                sectionNumber="31.4."
                body="Either party may seek any interim or preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s right or property pending the completion of arbitration."
              />
              <ListTermsAndConditions
                sectionNumber="31.5."
                body="Any and all legal, accounting, and other costs, fees, and expenses incurred by the prevailing party shall be borne by the non-prevailing party."
              />
            </View>
            <Text style={styles.sectionTitle}>32. Submission and Privacy</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="32.1."
                body="In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data, or proposals, including ideas for new or improved products, services, features, technologies, or promotions, you expressly agree that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of us without any compensation or credit to you whatsoever."
              />
              <ListTermsAndConditions
                sectionNumber="32.2."
                body="We and our affiliates shall have no obligation with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using such ideas."
              />
            </View>
            <Text style={styles.sectionTitle}>33. Typographic Errors</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="33.1."
                body="In the event of a product and/or service being listed at an incorrect price or with incorrect information due to typographical error, we shall have the right to refuse or cancel any orders placed for the product and/or service listed at the incorrect price."
              />
              <ListTermsAndConditions
                sectionNumber="33.2."
                body="We shall have the right to refuse or cancel any such order whether or not the order has been confirmed and your credit card charged."
              />
              <ListTermsAndConditions
                sectionNumber="33.3."
                body="If your credit card has already been charged for the purchase and your order is cancelled, we shall immediately issue a credit to your credit card account or other payment accounts in the amount of the charge."
              />
            </View>
            <Text style={styles.sectionTitle}>34. Miscellaneous</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="34.1."
                body="If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be unenforceable, the remainder of these Terms & Conditions will continue in full force and effect."
              />
              <ListTermsAndConditions
                sectionNumber="34.2."
                body="Any waiver of any provision of these Terms & Conditions will be effective only if in writing and signed by an authorized representative of us."
              />
              <ListTermsAndConditions
                sectionNumber="34.3."
                body="We will be entitled to injunctive or other equitable relief (without the obligation of posting any bond or surety) in the event of any breach or anticipatory breach by you."
              />
              <ListTermsAndConditions
                sectionNumber="34.4."
                body="We operate and control our Service from our office in Block 10 Lot 14 Victoria Village, Matina Aplaya, Davao City, Davao del Sur."
              />
              <ListTermsAndConditions
                sectionNumber="34.5."
                body="The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such distribution or use would be contrary to law or regulation."
              />
              <ListTermsAndConditions
                sectionNumber="34.6."
                body="Accordingly, those persons who choose to access our Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable."
              />
              <ListTermsAndConditions
                sectionNumber="34.7."
                body="These Terms & Conditions (which include and incorporate our Privacy Policy) contain the entire understanding, and supersedes all prior understandings, between you and us concerning its subject matter, and cannot be changed or modified by you."
              />
              <ListTermsAndConditions
                sectionNumber="34.8."
                body="The section headings used in this Agreement are for convenience only and will not be given any legal import."
              />
            </View>
            <Text style={styles.sectionTitle}>35. Disclaimer</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="35.1."
                body="We are not responsible for any content, code, or other imprecision."
              />
              <ListTermsAndConditions
                sectionNumber="35.2."
                body="We do not provide warranties or guarantees."
              />
              <ListTermsAndConditions
                sectionNumber="35.3."
                body="In no event shall we be liable for any special, direct, indirect, consequential, or incidental damages or any damages whatsoever, whether in an action of contract, negligence or other torts, arising out of or in connection with the use of the Service or the contents of the Service."
              />
              <ListTermsAndConditions
                sectionNumber="35.4."
                body="We reserve the right to make additions, deletions, or modifications to the contents of the Service at any time without prior notice."
              />
              <ListTermsAndConditions
                sectionNumber="35.5."
                body="Our Service and its contents are provided “as is” and “as available” without any warranty or representations of any kind, whether express or implied."
              />
              <ListTermsAndConditions
                sectionNumber="35.6."
                body="We are a distributor of and not a publisher of the content supplied by third parties; as such, we exercise no editorial control over such content and makes no warranty or representation as to the accuracy, reliability via our Service, or in the products provided as a part of, or otherwise in connection with, our Service, including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party rights."
              />
              <ListTermsAndConditions
                sectionNumber="35.7."
                body="No oral advice or written information given by us or any of its affiliates, employees, officers, directors, agents, or the like will create a warranty."
              />
              <ListTermsAndConditions
                sectionNumber="35.8."
                body="Price and availability information is subject to change without notice."
              />
              <ListTermsAndConditions
                sectionNumber="35.9."
                body="Without limiting the foregoing, we do not warrant that our Services will be uninterrupted, uncorrupted, timely, or error-free."
              />
            </View>
            <Text style={styles.sectionTitle}>36. Contact Us</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="36.1."
                body="Don’t hesitate to contact us if you have any questions."
              />
              <View style={styles.bodyWrapper1}>
                <Text style={styles.sectionNumber}>36.1.1.</Text>
                <Text style={styles.body}>
                  Via email:{' '}
                  <Text
                    style={{color: 'blue', textDecorationLine: 'underline'}}>
                    support@retriever.ph
                  </Text>
                  .
                </Text>
              </View>
              <View style={styles.bodyWrapper1}>
                <Text style={styles.sectionNumber}>36.1.1.</Text>
                <Text style={styles.body}>
                  Via this link:{' '}
                  <Text
                    style={{color: 'blue', textDecorationLine: 'underline'}}
                    onPress={() => Linking.openURL(`http://www.retriever.ph/`)}>
                    http://www.retriever.ph/
                  </Text>
                  .
                </Text>
              </View>
            </View>
            <Text style={styles.sectionTitle}>Additional Terms</Text>
            <View style={styles.bodyContainer}>
              <ListTermsAndConditions
                sectionNumber="1."
                body="Retriever Fetch"
              />
              <ListTermsAndConditions sectionNumber="a." body keyword />
              <ListTermsAndConditions
                sectionNumber="2."
                body="For Retriever Fetch Senders, you shall not send any delivery item containing any of the following:"
              />
              <ListTermsAndConditions
                sectionNumber="a."
                body="Hazardous, explosive, flammable and unsafe items (including powerbanks)"
                keyword
              />
              <ListTermsAndConditions
                sectionNumber="b."
                body="Valuable items"
                keyword
              />
            </View>
          </View>
        </ScrollView>
      </MainFrame>
    </MainScreen>
  );
};

const styles = StyleSheet.create({
  container: {
    margin: SPACING.medium,
  },
  title: {
    ...FONTS.bold,
    fontSize: SIZES._26px,
    alignSelf: 'center',
  },
  sectionTitle: {
    ...FONTS.bold,
    fontSize: SIZES._20px,
    marginTop: SPACING.small,
  },
  bodyContainer: {
    marginLeft: SPACING.large,
  },
  subBodyContainer: {
    marginLeft: windowHeight * 0.052,
  },
  bodyWrapper1: {
    flexDirection: 'row',
    marginTop: SPACING.x_small,
    marginLeft: windowHeight * 0.038,
  },
  sectionNumber: {
    ...FONTS.regular,
    fontSize: SIZES._14px,
    marginRight: SPACING.x_small,
  },
  body: {
    ...FONTS.regular,
    flex: 1,
    fontSize: SIZES._14px,
    textAlign: 'justify',
  },
});

export default TermsAndConditions;
