-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgQ7ZZwjOW1mQhvNfY
VT4BHEcEX0EikLnsjoRalP2FnUGgCgYIKoZIzj0DAQehRANCAATf+gJkkCpxDuOF
tAsjJYUY5tELWl/FbfEJ5OKPZRgr22jYXvXg83zTGHo+knFoH0LDrr4A9ZI9fK5u
dyqN/NcX
-----END PRIVATE KEY-----